# API entry point
jenkins:
  url: 'http://jenkins:8080'
  user: 'foo'
  pass: 'bar'

repos:
  - repo: Wikia/app
    events:
    - pull_request
    - pull_request_review_comment
    jobs:
    - job_name