# Chef generated config
# API entry point
jenkins: 'http://qa-s2:8080'
repos:
  # pull requests to dev
  - repo: Wikia/app
    events:
    - commit_comment
    - issue_comment
    - pull_request
    - pull_request_review_comment
    tags:
    - '@WikiaSparrow'
    jobs:
    - unitTests_js_branches